spring.application.name=speedXcar

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/speedxcar_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=VGVzdFNlY3JldEtleUZvclNwZWVkWGNhckJhY2tlbmQyMDI2VGVzdFNlY3JldA==
app.jwt.expiration-ms=86400000

# Server
server.port=8080